# Generated by Django 3.2.13 on 2022-07-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='yeosuRestaurant',
        ),
    ]
